### ISSUE TITLE
why is this using a fork of ctapipe?

### ISSUE THREAD

**Issue by dneise** [calispac/digicampipe#26]
I'm not well versed with what is usual in cta ... but I assumed one should rather use

https://github.com/cta-observatory/ctapipe

than a fork. I've looked at the fork and saw that it looks like a snapshot in time. 
Am I correct to assume, that digicam is using a fork to make sure upstream changes in ctapipe do not break digicampipe?

**Comment by calispac** [comment]
Yes we are using a snapshot of ctapipe to not break digicampipe. Actually we use mostly Container classes, display func. and geometry tools. We have to agree on what to do next. Maybe the best would be to have a branch of ctapipe and we try to implement in it what we need for SST-1M in a ctapipized way. But I don't know the opinions of CTApipe devs on that. 
We should contact them to ask what they think is best ?

**Comment by cocov** [comment]
My 2 cents:
I think a branch is not a problem for the cta dev (although better to ask them), that's how the other project handles it and I think it will make integration easier. What was painfull was to get the branch merged in the master because they were at the time in heavy dev period such that every two days there would be uncompatiblilities. 
If you don't mind I will transfer ownership of CTS to either @calispac or @superzerg, let me know which one (there is not really a good reason for me to keep it), and maybe then you could remove me from the members of the various cta sst1m project on github.

**Comment by dneise** [comment]
Looking at the README of digicampipe I think you could transfer ownership to @calispac.

In the long term Cyril could transfer ownership to cta-observtory, but this is a different question.

**Comment by calispac** [comment]
@cocov transfer it to @superzerg it makes more sense I guess.

**Comment by dneise** [comment]
should have kept my mouth shut, sorry

**Comment by dneise** [comment]
> Yes we are using a snapshot of ctapipe to not break digicampipe. Actually we use mostly Container classes, display func. and geometry tools.

I think, this can be tackled in a different way:
 1. fixing the required ctapipe version
 2. testing against external dependencies

--- 
Regarding 1:

Unfortunately ctapipe does not release very often: https://github.com/cta-observatory/ctapipe/releases

Last release (v0.5.2) is from July 31 and thus older than your snapshot, which is from Oct. 13

We could ask them to release more often, In particular, we could ask them to release your snapshot as v0.5.3 for example, so that digicampipe can safely require ctapipe==0.5.3 does not have to rely on private forks, of which nobody knows if they are "only snapshots" or not.

2. Testing ones dependencies:
I believe, using library code is better than rolling ones own solution. But external libraries can be updated and thus break your code. If one writes unit tests against the external library, one can make sure, this library behaves as expected. One even has the freedom to require always the newest version of the external library, since as soon as "they" make a code-breaking change, you know immediately and then you have the choice:
 - update your code, to support their changes, or
 - require the previous version of the external library.

1 and 2 are in a sense independent. Having tests is good, even when one requires a fixed version of ctapipe, since one might in the future want to manually update from e.g. v.0.5.3 to e.g. v0.6.0 and one wants to see as early as possible if 0.6.0 breaks digicam.

**Comment by dneise** [comment]
> Maybe the best would be to have a branch of ctapipe and we try to implement in it what we need for SST-1M in a ctapipized way. But I don't know the opinions of CTApipe devs on that.
We should contact them to ask what they think is best ?

Yes, I think we should ask them.

Should we open an issue in ctapipe for this?

**Comment by yrenier** [comment]
@superzerg  is my private account, please transfer it to @yrenier instead please.

**Comment by cocov** [comment]
My 2 cents:
I think a branch is not a problem for the cta dev (although better to ask them), that's how the other project handles it and I think it will make integration easier. What was painfull was to get the branch merged in the master because they were at the time in heavy dev period such that every two days there would be uncompatiblilities. 
If you don't mind I will transfer ownership of CTS to either @calispac or @superzerg, let me know which one (there is not really a good reason for me to keep it), and maybe then you could remove me from the members of the various cta sst1m project on github.
